compressionLevel: mixed

enableColors: true

enableGlobalCache: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs

npmRegistryServer: "https://registry.yarnpkg.com"
